# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edgar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/')),
                ('num_followers', models.IntegerField()),
                ('num_posts', models.IntegerField()),
                ('num_following', models.IntegerField()),
                ('insta_url', models.CharField(max_length=144)),
                ('fb_url', models.CharField(max_length=144)),
                ('email', models.CharField(max_length=144)),
            ],
        ),
    ]
