# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0002_auto_20161207_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edgar',
            name='num_followers',
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
    ]
