# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 15:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0006_remove_edgar_insta_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='edgar',
            name='fb_image',
        ),
    ]
