# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginapp', '0007_remove_edgar_fb_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgar',
            name='fb_image',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='websiteimages/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='edgar',
            name='insta_image',
            field=models.ImageField(blank=True, max_length=144, null=True, upload_to='websiteimages/%Y/%m/%d/'),
        ),
    ]
