# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
