# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-16 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20161115_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default=None, max_length=144),
        ),
    ]
