# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-07 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20161115_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(max_length=144, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
