# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TodoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=144)),
                ('is_done', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
            ],
        ),
    ]
